### ISSUE TITLE
Inconsistent Function Interface Definitions

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/sdf_tools#10]
The output of `GridIndexToLocation` cannot be used as input for functions such as `Get`, `GetGradient`, `EstimateDistance` etc.

**Comment by calderpg** [comment]
Several thoughts:

- As is, `LocationToGridIndex` and `GridIndexToLocation` return `std::vector<double>` so that an input outside the bounds of the grid can be detected. In such cases, an empty vector is returned. For consistency, both interfaces use `std::vector` rather than using `Eigen::VectorXd` for `GridIndexToLocation` (there is no equivalently handy `Eigen::VectorXli`).

- Switching to a fixed-size Eigen type is out of the question without wrapping in an option type, and given that some of these functions are called in every query, the additional overhead of boxing/unboxing in an option type is probably a bad idea.

- All functions lke `Get`, `GetGradient`, etc that require a fixed number of arguments take them that way. Adding additional wrapper functions that require size checks on variable-sized containers to retrieve their arguments is a bad idea, and also impedes the ability of the compiler to optimize through arguments passed in registers or the stack, since all variable-sized containers must store data in the heap.

**Comment by dmcconachie** [comment]
Is there any reason the `LocationToGridIndex` and 'GridIndexToLocation` functions can't use the same return style as `Get3d`, or `EstimateDistance3d`? I.e. a pair with {data, valid}? Then one could compose these functions as:

```
assert(LocationToGridIndex(GridIndexToLocation(grid_index).first).first == grid_index)
```

at least for cases where everything is valid.

**Comment by calderpg** [comment]
I'm hesitant to optimize for code-writting efficiency the case of in-grid queries when it makes it much easier to lose track of out-of-grid results. I'm well aware of how easy it is to ignore checking `.second` on all those return types. If we switch to a system where the return types are `std::pair<GRID_INDEX, bool>` and `std::pair<Eigen::Vector4d, bool>`, then we face the issue of **no** value for the `.first` that is "safe" for missuse. Zero is a potentially valid value, random is a potentially valid value, and NAN is an unsafe signalling value for a library written to let you compile with `-Ofast` if you dare. The advantage of vector return types is that either you as a programmer have to explicitly ask for `[0]`, `[1]`, etc, or you use a safe wrapper function that ensures the size check is performed. There's no way to "accidentally" end up with a valid program that tries to use invalid results.

Alternatively, we abandon entirely the idea that these functions should always return valid indices or locations within the grid. `LocationToGridIndex` can return out-of-bounds `GRID_INDEX` values and any thoughtful code using it should already not blindly trust that all possible `GRID_INDEX` types are valid. Likewise, `GridIndexToLocation` can return an `Eigen::Vector4d` location corresponding to an unbounded grid with positive and negative indices. Indeed, such functions are of use for applying fixed discretization, and an unbounded `LocationToGridIndex` is used in `fast_kinematic_simulator` and `iiwa_reachability_prm` to implement discretized self-collision checking.

In practice, the sane options are either to leave it the way it is, and use the extra effort involved in translating return types to ensure that users don't ignore validity concerns, **or** to give up the idea altogether that these functions should incorporate checking grid bounds at all. Any intermediate solution seems like bad design that optimizes for the best case while making the worst case more likely to bite people.

**Comment by dmcconachie** [comment]
It's not about optimizing for code-writing efficiency. It's about providing a consistent interface, and making the code more *readable*. A minimum change that would improve matters but would still leave a mess of different interfaces behind (`Get`, `GetSafe`, `GetGradient` all have different interface styles), would be to add additional accessors that consume `std::vector<double>` and `std::vector<whatever type you're using for indices>` which check the size of the incoming vector, same as anyone manually doing this conversion would have to do.

The goal is to have the output of `GridIndexToLocation` and similar functions be valid input to other functions that consume a location (and vice versa for location to index functions). This goal is entirely reasonable.

**Comment by bsaund** [comment]
Weighing in here:
This seems like a great use for [std::optional](http://en.cppreference.com/w/cpp/utility/optional)

The fundamental problem is the cardinality of the return type not matching the cardinality of the data we want to communicate.
With `std::pair<data, valid>`, if `valid==false` then `data` has no meaning, but since it is easy to use it incorrectly.
`std::vector` is arguably worse, since the cardinality is huge (inf) but only size 0, 3, or 4 vectors have any meaning.

My understanding is std::optional is very fast, probably faster than making a std::vector. It is also more clear to read.



Regarding indices as a vector vs. 3 separate arguments vs. something else:
I really don't think efficiency is a _significant_ issue here. (Do some tests to prove me wrong).
Maybe I'd go so far as to define a type GridIndices

**Comment by bsaund** [comment]
As dale pointed out, std::optional is c++17, so use our Maybe function.

**Comment by bsaund** [comment]
Ha, reading more of the code now. There is a GridIndex :)

**Comment by calderpg** [comment]
The solution that "solves" consistency is what I suggested earlier:

Abandon entirely the idea that these functions should always return valid indices or locations within the grid. LocationToGridIndex can return out-of-bounds GRID_INDEX values and any thoughtful code using it should already not blindly trust that all possible GRID_INDEX types are valid. Likewise, GridIndexToLocation can return an Eigen::Vector4d location corresponding to an unbounded grid with positive and negative indices. Equivalent functions are already used in fast_kinematic_simulator and iiwa_reachability_prm to implement discretized self-collision checking.

Here you will always have "valid" data that the SDF, CollisionMapGrid,, etc will always properly handle. Problem solved.

**Comment by calderpg** [comment]
More to the point here, this is an [issue](https://github.com/UM-ARM-Lab/arc_utilities/issues/29) that actually needs to be resolved in `VoxelGrid` where these functions are actually implemented, rather than the wrappers in `sdf_tools`

**Comment by dmcconachie** [comment]
I think I'd be fine with this proposed solution, I would need to look at it closer though (sometime after Nov. 1st (or possibly Nov. 13th)).
