### ISSUE TITLE
Collision Map SDF generator does not account for OOB value being "in collision"

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/sdf_tools#11]
I'm not sure what the right way is to handle this, but is may be worth investigating at some point. One naive solution might be to bloat the map by 1 cell in each direction, filling in the boundary with the OOB value, generate the SDF as per usual, and then shrink the SDF by 1 cell.

**Comment by calderpg** [comment]
Is there a meaningful reason to have a collision map where the boundary cells are empty but OOB is filled? The simple fix is just to always have the outside shell of the collision map filled. Alternatively, if we want to avoid that, the way to address this is to set the two bucket grids used in SF generation to have an extra filled cell on all sides, and then just trim that off when returning the SDF. This could be slightly risky in that translating between the original grid and a +2 cell grid might expose some numerical issues on cell boundaries.

**Comment by dmcconachie** [comment]
The reason I want it is actually for visualization: I want an outer boundary that is "in collision" but is not visible when exported, so maybe that's a better place to make the fix. I see two ways to modify `CollisionMapGrid::ExportForDisplay`:
1. Different color for each component
2. Different namespace for each component
It's not clear to me which would be better, but either of these is I think cleaner than futzing with the SDF generation code.

**Comment by calderpg** [comment]
That's why tagged_object_collision_map exists, so you can create different "objects" out of the obstacle cells that receive different colors.

**Comment by dmcconachie** [comment]
Well, then I guess we need some documentation somewhere.

**Comment by calderpg** [comment]
Per-component handling does not ensure that a boundary is separate from interior objects, since those interior objects may touch the outside of the grid. The only solution is to identify which "object" a given cell is a member of, which is what the tagged_object_collision_map does with per-cell object id values and implicit/explicit per-object coloring rules - by default, object 0 is not visualized, and you can provide desired colors for objects or let it auto-color them.
