### ISSUE TITLE
Input validity checking for Eigen::Vector4d types

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/sdf_tools#14]
We should consider adding in input sanitization for the Vector4d versions of functions. The best way may be to enable debug vs release versions of the library with and without these checks.

**Comment by calderpg** [comment]
This change should be largely accomplished in the underlying VoxelGrid class. There are very few places in sdf_tools that an Eigen::Vector4d is handled without being passed into VoxelGrid immediately, so we can probably put all of the safety checks into the parent class.

I'm considering moving all the VoxelGrid and derived classes to use exceptions for sanity checks rather than asserts, which might have a bearable performance impact for something like this to be 'always on'.

**Comment by calderpg** [comment]
Modern compiler support is such that the performance impact of exceptions that "never happen" can cause less runtime cost than asserts that are always evaluated.
